import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const {data:src}=JSON.parse(await fs.readFile('source.json','utf8'));
const out='outputs/qse_multivilles'; await fs.mkdir(out,{recursive:true});
const wb=Workbook.create();
const names=['Tableau de bord','Actions','Plans de prévention','Contrôles qualité','Échéances','Réclamations','Suivi mensuel','Paramètres','Analyse et mode emploi'];
const sheets=Object.fromEntries(names.map(n=>[n,wb.worksheets.add(n)]));
const C={navy:'#243B53',blue:'#3268A8',amber:'#FFF2CC',ink:'#243746',muted:'#637588',pale:'#EDF2F7',red:'#FCE4E4',green:'#E2F0E8'};
const end=505;
const serial=v=>{if(!v||typeof v!=='string')return null;let s=v.trim(),y,m,d;if(/^\d{4}-\d\d-\d\d/.test(s)){[y,m,d]=s.slice(0,10).split('-').map(Number);}else if(/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(s)){[d,m,y]=s.split('/').map(Number);}else return null;let dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCMonth()===m-1&&dt.getUTCDate()===d?(dt-Date.UTC(1899,11,30))/86400000:null;};
const val=(s,a,v)=>s.getRange(a).values=[[v]];
const form=(s,a,v)=>s.getRange(a).formulas=[[v]];
function title(s,t,last='L',rows=35){s.showGridLines=false;s.getRange(`A1:${last}${rows}`).format.font={name:'Arial',size:10,color:C.ink};s.getRange(`A1:${last}${rows}`).format.rowHeight=23;s.getRange(`A1:${last}${rows}`).format.verticalAlignment='center';val(s,'A2',t);s.getRange('A2').format.font={name:'Arial',size:16,bold:true,color:C.navy};s.getRange(`A3:${last}3`).format.borders={bottom:{style:'thin',color:C.navy}};}
function header(s,range){s.getRange(range).format={fill:C.navy,font:{name:'Arial',size:10,color:'#FFFFFF',bold:true},wrapText:true,rowHeight:38,verticalAlignment:'center',horizontalAlignment:'center'};}
function table(s,heads,rows,name,widths){let last=String.fromCharCode(64+heads.length);title(s,s.name??name,last,end);s.getRange(`A5:${last}5`).values=[heads];if(rows.length)s.getRange(`A6:${last}${rows.length+5}`).values=rows;s.tables.add(`A5:${last}${end}`,true,name);s.getRange(`A6:${last}${end}`).format.fill=C.amber;header(s,`A5:${last}5`);widths.forEach((w,i)=>s.getRangeByIndexes(0,i,end,1).format.columnWidth=w);s.freezePanes.freezeRows(5);s.freezePanes.freezeColumns(2);val(s,'A4','Source : Lille_TDB QSE.xlsm. Saisie jaune, calculs gris. 500 lignes extensibles. Filtrer Ville.');}
function calc(s,col,f){form(s,`${col}6`,f);s.getRange(`${col}6:${col}${end}`).fillDown();s.getRange(`${col}6:${col}${end}`).format.fill=C.pale;}
function dates(s,cols){for(const c of cols)s.getRange(`${c}6:${c}${end}`).setNumberFormat('dd/mm/yyyy');}
function status(s,col){let r=s.getRange(`${col}6:${col}${end}`);for(const t of ['Retard','Expiré','À compléter','Incohérent','Doublon'])r.conditionalFormats.add('containsText',{text:t,format:{fill:C.red,font:{color:'#9C2525'}}});r.conditionalFormats.add('containsText',{text:'À renouveler',format:{fill:'#FCE8C3',font:{color:'#875900'}}});}
const range=(s,c)=>`'${s}'!$${c}$6:$${c}$${end}`;
const city=`'Tableau de bord'!$B$5`,asof=`'Tableau de bord'!$F$5`;

// Parameters are editable controls, not invented targets.
const p=sheets['Paramètres'];title(p,'Paramètres communs','H',40);p.getRange('A1:A40').format.columnWidth=29;p.getRange('B1:B40').format.columnWidth=23;p.getRange('D1:D40').format.columnWidth=45;p.getRange('E1:E40').format.columnWidth=18;p.getRange('F1:H40').format.columnWidth=22;
p.getRange('A5:B5').values=[['Villes disponibles','Mode de saisie']];header(p,'A5:B5');p.getRange('A6:A25').format.fill=C.amber;val(p,'A6','Lille');val(p,'B6','Ajouter une ville dessous');
p.getRange('D5:E5').values=[['Réglage','Valeur']];header(p,'D5:E5');p.getRange('D6:E9').values=[['Préavis échéances (jours)',30],['Objectif qualité (fraction de 1)',null],['Objectif PdP complet (fraction de 1)',null],['Délai réponse RC (jours calendaires)',null]];p.getRange('E6:E9').format.fill=C.amber;p.getRange('E7:E8').setNumberFormat('0.0%');val(p,'D11','Objectifs et délai RC à définir par votre organisation.');val(p,'D12','Préavis de 30 jours proposé et modifiable.');val(p,'D14','La date de situation pilote les alertes de stock.');val(p,'D15','Le mois pilote les contrôles, les RC et le suivi mensuel.');
const monthlyHeads=['Ville','Mois','Produits écolabellisés (%)','Papier (feuilles)','Électricité (kWh)','CO2 (kg)','Distance (km)','AT avec arrêt','AT analysés','Audits prévus','Audits réalisés','Satisfaction (%)','Avis suivis (stock)','Avis clôturés (stock)','Urgences à traiter (stock)','Urgences traitées (stock)','Commentaires / source','Contrôle saisie'];
const monthly=[];for(let m=1;m<=12;m++)monthly.push(['Lille',serial(`2026-${String(m).padStart(2,'0')}-01`),m<=2?src['TX ECO'][m+1][1]:null,...Array(13).fill(null),m<=2?`TX ECO!B${m+2}. Taux source, base de pondération non disponible.`:null,null]);
const restrictions=src['Restrictions'].slice(10).filter(r=>r[1]);monthly[8][12]=restrictions.length;monthly[8][13]=restrictions.filter(r=>String(r[11]).toLowerCase()==='cloturée').length;monthly[8][16]='Restrictions!A11:M34 : état constaté au 14/09/2026. Les autres mesures restent à renseigner.';
const ms=sheets['Suivi mensuel'];table(ms,monthlyHeads,monthly,'Mensuel',[20,14,20,18,20,16,18,16,16,16,16,18,18,18,20,20,64,26]);dates(ms,['B']);ms.getRange(`C6:C${end}`).setNumberFormat('0.0%');ms.getRange(`L6:L${end}`).setNumberFormat('0.0%');calc(ms,'R',`=IF(A6="","",IF(B6="","À compléter",IF(COUNTIFS($A$6:$A$${end},A6,$B$6:$B$${end},B6)>1,"Doublon ville/mois",IF(OR(AND(ISNUMBER(H6),ISNUMBER(I6),I6>H6),AND(ISNUMBER(M6),ISNUMBER(N6),N6>M6),AND(ISNUMBER(O6),ISNUMBER(P6),P6>O6)),"Incohérent",""))))`);status(ms,'R');

const actions=[];for(const n of ["Plan d'actions","Plan d'actions - Audit chantier"])src[n].slice(15).forEach((r,i)=>{if(r[5])actions.push(['Lille',`${n.includes('chantier')?'AC':'AP'}-${String(r[0]).padStart(3,'0')}`,n.includes('chantier')?'Audit chantier':'Processus',r[1],serial(r[2]),r[4],r[5],r[6],serial(r[7]),serial(r[8]),r[10],r[11],null,null,`${n}!A${i+16}:L${i+16}`,null]);});
const ac=sheets.Actions;table(ac,['Ville','ID action','Famille','Origine / site','Ouverture','Problème','Action à réaliser','Responsable','Échéance','Réalisation','Évaluation','Preuves / observations','Avancement calculé','Retard (jours)','Source','Contrôle saisie'],actions,'ActionsQSE',[18,14,18,26,14,52,66,31,14,14,18,58,23,16,43,24]);dates(ac,['E','I','J']);calc(ac,'M',`=IF(A6="","",IF(G6="","À compléter",IF(AND(ISNUMBER(J6),J6<=${asof}),"Réalisée",IF(I6="","À compléter",IF(I6<${asof},"Retard","À venir")))))`);calc(ac,'N',`=IF(OR(A6="",I6=""),"",IF(M6="Retard",${asof}-I6,0))`);calc(ac,'P',`=IF(A6="","",IF(OR(B6="",G6="",H6="",E6=""),"À compléter",IF(COUNTIFS($A$6:$A$${end},A6,$B$6:$B$${end},B6)>1,"Doublon ID",IF(AND(ISNUMBER(J6),J6<E6),"Incohérent",""))))`);status(ac,'M');status(ac,'P');ac.getRange(`K6:K${end}`).dataValidation={rule:{type:'list',values:['Non vérifiée','Efficace','A revoir']}};for(const c of ['F','G','L'])ac.getRange(`${c}6:${c}${actions.length+5}`).format.wrapText=true;for(let i=0;i<actions.length;i++){let r=actions[i];ac.getRange(`A${i+6}:P${i+6}`).format.rowHeight=Math.max(48,Math.ceil(Math.max(String(r[5]??'').length/65,String(r[6]??'').length/82,String(r[11]??'').length/72))*15+10);}

const pdp=src['Suivi PdP'].slice(11).flatMap((r,i)=>r[1]?[['Lille',`PDP-${i+12}`,r[0],r[1],r[3],serial(r[8]),r[13],r[16],r[17],r[18],r[19],r[15],r[23],null,null,null,`Suivi PdP!A${i+12}:X${i+12}`,null]]:[]);
const pd=sheets['Plans de prévention'];table(pd,['Ville','ID suivi','OTP','Client / site','Responsable','Échéance source','Analyse faite','Analyse envoyée','Signé ISOR','Signé client','Commenté agents','DTA','Commentaires','Jours restants','État échéance','PdP complet','Source','Contrôle OTP'],pdp,'PlansPrevention',[18,15,18,43,21,18,17,18,17,17,20,14,52,17,24,18,33,24]);dates(pd,['F']);calc(pd,'N',`=IF(A6="","",IF(ISNUMBER(F6),F6-${asof},""))`);calc(pd,'O',`=IF(A6="","",IF(ISNUMBER(F6),IF(N6<0,"Expiré",IF(N6<='Paramètres'!$E$6,"À renouveler","À jour")),"À compléter"))`);calc(pd,'P',`=IF(A6="","",IF(AND(ISNUMBER(F6),F6>${asof},G6="Oui",H6="Oui",I6="Oui",J6="Oui",K6="Oui"),1,0))`);calc(pd,'R',`=IF(A6="","",IF(C6="","OTP manquant",IF(COUNTIFS($A$6:$A$${end},A6,$C$6:$C$${end},C6)>1,"Doublon OTP","")))`);for(const c of ['G','H','I','J','K','L'])pd.getRange(`${c}6:${c}${end}`).dataValidation={rule:{type:'list',values:['Oui','Non','NC']}};status(pd,'O');status(pd,'R');

const quality=src['Indice qualité et nb contrôle'].slice(2).flatMap((r,i)=>r[0]?[['Lille',`CQ-${i+3}`,r[0],r[1],r[3],serial(r[5]),typeof r[2]==='number'?r[2]/100:null,`Indice qualité et nb contrôle!A${i+3}:F${i+3}`,null]]:[]);
const qs=sheets['Contrôles qualité'];table(qs,['Ville','ID contrôle','Site','Type','Contrôleur','Date réalisée','Note (%)','Source','Contrôle saisie'],quality,'Controles',[18,17,38,28,24,18,18,60,26]);dates(qs,['F']);qs.getRange(`G6:G${end}`).setNumberFormat('0.0%');calc(qs,'I',`=IF(A6="","",IF(OR(B6="",C6="",F6="",NOT(ISNUMBER(G6))),"À compléter",IF(OR(G6<0,G6>1),"Incohérent",IF(COUNTIFS($A$6:$A$${end},A6,$B$6:$B$${end},B6)>1,"Doublon ID",""))))`);status(qs,'I');

const deadlines=[];src['Suivi Habilitations'].slice(8).forEach((r,i)=>{if(r[0])deadlines.push(['Lille',`HAB-${i+9}`,'Habilitation',r[2],`${r[0]} ${r[1]}`,r[3],serial(r[8]),serial(r[9]),r[6],r[13],null,null,`Suivi Habilitations!A${i+9}:R${i+9}`]);});src['Suivi VPO'].slice(19,77).forEach((r,i)=>{if(r[0])deadlines.push(['Lille',`VPO-${i+20}`,'VPO',r[2],r[7],r[0],serial(r[4]),serial(r[6]),r[8],r[10],null,null,`Suivi VPO!A${i+20}:K${i+20}`]);});src['Exercices Obligatoires'].slice(14).forEach((r,i)=>{if(r[0])deadlines.push(['Lille',`EX-${i+15}`,'Exercice',r[1],r[3],r[0],serial(r[2]),serial(r[8]),r[4],r[6],null,null,`Exercices Obligatoires!A${i+15}:J${i+15}`]);});
const es=sheets['Échéances'];table(es,['Ville','ID suivi','Famille','Site','Personne / vérificateur','Objet','Dernière réalisation','Prochaine échéance','Qualification source','Commentaires','Jours restants','État échéance','Source'],deadlines,'Echeances',[18,16,19,27,34,46,20,20,26,58,18,24,44]);dates(es,['G','H']);calc(es,'K',`=IF(A6="","",IF(ISNUMBER(H6),H6-${asof},""))`);calc(es,'L',`=IF(A6="","",IF(ISNUMBER(H6),IF(K6<0,"Expiré",IF(K6<='Paramètres'!$E$6,"À renouveler","À jour")),"À compléter"))`);status(es,'L');

const complaints=src['Tableau suivi RC '].slice(2).flatMap((r,i)=>r[4]?[['Lille',`RC-${r[0]}`,r[4],r[6],r[1],serial(r[2]),serial(r[3]),serial(r[11]),r[7],r[8],r[18],r[21],null,null,`Tableau suivi RC !A${i+3}:V${i+3}`]]:[]);
const rs=sheets.Réclamations;table(rs,['Ville','ID dossier','Client','Catégorie','Canal','Émission','Réception','Réponse','Responsable','Motif / détail','Action menée','État action source','Délai (jours)','État réponse','Source'],complaints,'Reclamations',[18,16,35,20,22,16,16,16,29,66,44,24,18,26,42]);dates(rs,['F','G','H']);calc(rs,'M',`=IF(A6="","",IF(AND(ISNUMBER(G6),ISNUMBER(H6)),H6-G6,""))`);calc(rs,'N',`=IF(A6="","",IF(NOT(ISNUMBER(G6)),"Réception manquante",IF(AND(ISNUMBER(H6),H6<G6),"Incohérent",IF('Paramètres'!$E$9="",IF(ISNUMBER(H6),"Répondue / cible absente","Sans réponse / cible absente"),IF(ISNUMBER(H6),IF(M6<='Paramètres'!$E$9,"Dans le délai","Hors délai"),IF(${asof}-G6>'Paramètres'!$E$9,"Retard","En attente"))))))`);status(rs,'N');rs.getRange(`J6:K${complaints.length+5}`).format.wrapText=true;for(let i=0;i<complaints.length;i++)rs.getRange(`A${i+6}:O${i+6}`).format.rowHeight=Math.max(40,Math.ceil(String(complaints[i][9]??'').length/82)*15+10);

// Dashboard: monthly activity and current registers explicitly separated.
const db=sheets['Tableau de bord'];title(db,'Tableau de bord QSE','L',52);db.tabColor=C.navy;db.getRange('A1:A52').format.columnWidth=42;db.getRange('B1:B52').format.columnWidth=19;db.getRange('C1:C52').format.columnWidth=17;db.getRange('D1:D52').format.columnWidth=24;db.getRange('E1:E52').format.columnWidth=3;db.getRange('F1:F52').format.columnWidth=27;db.getRange('G1:L52').format.columnWidth=12;
val(db,'A5','Ville');val(db,'B5','Lille');val(db,'D5','Situation au');val(db,'F5',serial('2026-09-14'));db.getRange('F5').setNumberFormat('dd/mm/yyyy');val(db,'A6','Mois des indicateurs');val(db,'B6',serial('2026-07-01'));db.getRange('B6').setNumberFormat('mm/yyyy');val(db,'D6','Année des tendances');form(db,'F6','=YEAR(B6)');for(const a of ['B5','B6','F5'])db.getRange(a).format.fill=C.amber;db.getRange('B5').dataValidation={rule:{type:'list',formula1:"'Paramètres'!$A$6:$A$25"}};
db.getRange('A9:D9').values=[['Activité du mois','Résultat','Objectif','Lecture']];header(db,'A9:D9');
const qr=range('Contrôles qualité','A'), qdate=range('Contrôles qualité','F'),qnote=range('Contrôles qualité','G');const qcrit=`${qr},$B$5,${qdate},">="&$B$6,${qdate},"<"&EDATE($B$6,1)`;
val(db,'A10','Contrôles qualité enregistrés');form(db,'B10',`=IF(COUNTIFS(${qcrit})=0,"n.d.",COUNTIFS(${qcrit}))`);val(db,'A11','Indice qualité (moyenne des notes)');form(db,'B11',`=IF(COUNTIFS(${qcrit},${qnote},">=0")=0,"n.d.",SUMIFS(${qnote},${qcrit})/COUNTIFS(${qcrit},${qnote},">=0",${qnote},"<>"))`);db.getRange('B11:C11').setNumberFormat('0.0%');form(db,'C11',`=IF('Paramètres'!E7="","",'Paramètres'!E7)`);form(db,'D11','=IF(NOT(ISNUMBER(B11)),"Données absentes",IF(C11="","Cible à définir",IF(B11>=C11,"Objectif atteint","Sous objectif")))');
const rc=range('Réclamations','A'),rd=range('Réclamations','G');val(db,'A12','Réclamations reçues (catégorie seule)');form(db,'B12',`=IF(COUNTIFS(${rc},$B$5,${rd},">="&$B$6,${rd},"<"&EDATE($B$6,1),${range('Réclamations','D')},"Réclamation")=0,"n.d.",COUNTIFS(${rc},$B$5,${rd},">="&$B$6,${rd},"<"&EDATE($B$6,1),${range('Réclamations','D')},"Réclamation"))`);
function monthValue(col){let crit=`${range('Suivi mensuel','A')},$B$5,${range('Suivi mensuel','B')},$B$6`;return `=IF(COUNTIFS(${crit})>1,"Doublon",IF(COUNTIFS(${crit},${range('Suivi mensuel',col)},">=0",${range('Suivi mensuel',col)},"<>")=0,"n.d.",SUMIFS(${range('Suivi mensuel',col)},${crit})))`;}
for(const [r,label,col] of [[13,'Produits écolabellisés','C'],[14,'Papier consommé (feuilles)','D'],[15,'Électricité (kWh)','E'],[16,'Émissions du parc auto (kg CO2)','F'],[17,'Distance parcourue (km)','G'],[18,'AT avec arrêt','H'],[19,'AT analysés','I'],[20,'Audits réalisés','K'],[21,'Satisfaction client','L']]){val(db,`A${r}`,label);form(db,`B${r}`,monthValue(col));}db.getRange('B13').setNumberFormat('0.0%');db.getRange('B21').setNumberFormat('0.0%');
db.getRange('A24:D24').values=[['Registres à la date de situation','Résultat','Base','Lecture']];header(db,'A24:D24');
const cc=(sn,col,cond)=>`COUNTIFS(${range(sn,'A')},$B$5${col?`,${range(sn,col)},${cond}`:''})`;
const metrics=[
 [25,'Actions réalisées',cc('Actions','M','"Réalisée"'),cc('Actions',null,null)],
 [26,'Actions en retard',cc('Actions','M','"Retard"'),null],
 [27,'Actions sans échéance exploitable',cc('Actions','M','"À compléter"'),null],
 [28,'PdP complets et valides',cc('Plans de prévention','P','1'),cc('Plans de prévention',null,null)],
 [29,'PdP expirés',cc('Plans de prévention','O','"Expiré"'),null],
 [30,'PdP sans échéance',cc('Plans de prévention','O','"À compléter"'),null],
 [31,'Habilitations / VPO / exercices expirés',cc('Échéances','L','"Expiré"'),null],
 [32,'Échéances dans le préavis',cc('Échéances','L','"À renouveler"'),null],
 [33,'Échéances manquantes',cc('Échéances','L','"À compléter"'),null],
 ];
for(const [r,l,f,den]of metrics){val(db,`A${r}`,l);let sn=r<=27?'Actions':r<=30?'Plans de prévention':'Échéances';form(db,`B${r}`,`=IF(${cc(sn,null,null)}=0,"n.d.",${den?`${f}/${den}`:f})`);if(den){form(db,`C${r}`,`=${den}`);db.getRange(`B${r}`).setNumberFormat('0.0%');}else form(db,`D${r}`,`=IF(NOT(ISNUMBER(B${r})),"Données absentes",IF(B${r}>0,"À traiter","Aucun dans le registre"))`);}
form(db,'D28',`=IF(NOT(ISNUMBER(B28)),"Données absentes",IF('Paramètres'!E8="","Cible à définir",IF(B28>='Paramètres'!E8,"Objectif atteint","Sous objectif")))`);
val(db,'A35','n.d. : aucune mesure exploitable. Un registre vide ne prouve pas une absence d’événements.');val(db,'A36','Les stocks décrivent les registres actuels. Changer la date ne reconstitue pas un historique.');val(db,'A37','PdP complet : analyse faite et envoyée, deux signatures, commentaire agents, échéance > date de situation.');val(db,'A39','Avis suivis (stock déclaré)');form(db,'B39',monthValue('M'));form(db,'B40',monthValue('N'));val(db,'A40','Avis clôturés (stock déclaré)');
// Visible chart data lives below the main dashboard.
db.getRange('A44:D44').values=[['Mois','Indice qualité','Contrôles','Produits écolabellisés']];header(db,'A44:D44');
const months=['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sep','Oct','Nov','Déc'];
for(let i=0;i<12;i++){let r=45+i;val(db,`A${r}`,months[i]);let dt=`DATE($F$6,${i+1},1)`,crit=`${qr},$B$5,${qdate},">="&${dt},${qdate},"<"&EDATE(${dt},1)`;form(db,`B${r}`,`=IF(COUNTIFS(${crit},${qnote},">=0")=0,"",SUMIFS(${qnote},${crit})/COUNTIFS(${crit},${qnote},">=0",${qnote},"<>"))`);form(db,`C${r}`,`=IF(COUNTIFS(${crit})=0,"",COUNTIFS(${crit}))`);let mcrit=`${range('Suivi mensuel','A')},$B$5,${range('Suivi mensuel','B')},${dt}`;form(db,`D${r}`,`=IF(COUNTIFS(${mcrit})>1,"",IF(COUNTIFS(${mcrit},${range('Suivi mensuel','C')},">=0",${range('Suivi mensuel','C')},"<>")=0,"",SUMIFS(${range('Suivi mensuel','C')},${mcrit})))`);}db.getRange('B45:B56').setNumberFormat('0.0%');db.getRange('D45:D56').setNumberFormat('0.0%');
let chart=db.charts.add('bar',db.getRange('A44:B56'));chart.title='Indice qualité mensuel (%)';chart.hasLegend=false;chart.setPosition('F9','M23');chart.titleTextStyle.typeface='Arial';chart.titleTextStyle.fontSize=14;chart.yAxis={numberFormatCode:'0%',numberFormatSourceLinked:false};
db.getRange('F26:G26').values=[['Actions','Nombre']];header(db,'F26:G26');['Réalisée','Retard','À venir','À compléter'].forEach((t,i)=>{val(db,`F${27+i}`,t);form(db,`G${27+i}`,`=IF(${cc('Actions',null,null)}=0,"",${cc('Actions','M',`F${27+i}`)})`);});let ch2=db.charts.add('bar',db.getRange('F26:G30'));ch2.title='Avancement des actions';ch2.hasLegend=false;ch2.setPosition('I25','P39');ch2.titleTextStyle.typeface='Arial';ch2.titleTextStyle.fontSize=14;
for(const sn of ['Actions','Plans de prévention','Contrôles qualité','Échéances','Réclamations','Suivi mensuel'])sheets[sn].getRange(`A6:A${end}`).dataValidation={rule:{type:'list',formula1:"'Paramètres'!$A$6:$A$25"}};
for(const c of ['D10:D33']){db.getRange(c).conditionalFormats.add('containsText',{text:'À traiter',format:{fill:C.red,font:{color:'#9C2525'}}});db.getRange(c).conditionalFormats.add('containsText',{text:'Sous objectif',format:{fill:C.red,font:{color:'#9C2525'}}});}

const guide=sheets['Analyse et mode emploi'];title(guide,'Analyse du fichier et utilisation','D',72);guide.getRange('A1:A72').format.columnWidth=33;guide.getRange('B1:B72').format.columnWidth=112;guide.getRange('C1:C72').format.columnWidth=54;guide.getRange('D1:D72').format.columnWidth=18;
const notes=[
 ['Source','Lille_TDB QSE.xlsm. Analyse des valeurs, dates, formules et tableaux présents. Aucune macro exécutée.','Classeur original conservé.'],
 ['Périmètre','Pilotage QSE d’agence. Reprise des registres exploitables et création d’un modèle commun par ville.',''],
 ['Période initiale','Juillet 2026 est proposé car les 49 contrôles détaillés sont datés de ce mois. Situation des registres au 14/09/2026.','Contrôles qualité et cellules TODAY source'],
 ['Qualité','49 contrôles, moyenne 95,2606 %. Un ancien TCD affiche 101 contrôles et un autre une moyenne de 94,0828 %. Les TCD ne sont pas utilisés.','Indice qualité et nb contrôle!A3:F51 ; Indicateurs!C78'],
 ['Plans de prévention','51 lignes client conservées. OTP C/005847 présent deux fois. Aucun regroupement automatique : confirmer si les deux lignes désignent le même périmètre.','Suivi PdP!A34:B34 et A45:B45'],
 ['Définition PdP corrigée','La formule source « signé et commenté » ne vérifie pas la signature client. Le nouvel indicateur exige explicitement les deux signatures.','Suivi PdP!J4'],
 ['Échéances PdP','Les échéances enregistrées sont reprises telles quelles. La durée de 99 ans de l’agence doit être confirmée. Les jours restants sont recalculés uniformément.','Suivi PdP!H12:I12 ; J42, J53'],
 ['Dates','Des dates RC sont stockées en texte. Les dates valides sont converties en dates Excel. La date de démarrage 31/04/2024 est impossible.','Tableau suivi RC !L3 ; Suivi PdP!F44'],
 ['Erreurs de calcul','14 cellules contiennent des erreurs enregistrées : divisions par zéro, références invalides et valeurs non exploitables. Elles ne sont pas propagées.','Indicateurs (2), Compilation (2), PdP (1), RC (2), Papier (7)'],
 ['Actions','Les lignes réellement renseignées sont reprises avec un ID AP ou AC. La date de réalisation pilote la clôture. L’efficacité reste une évaluation distincte.','Deux plans d’actions, lignes à partir de 16'],
 ['Efficacité des actions','Les totaux source d’efficacité dépassent les actions renseignées. Filtrer les actions réalisées sans évaluation avant de conclure à leur efficacité.','Plans d’actions!L5:L8'],
 ['Habilitations et VPO','Les échéances concernent les habilitations, les VPO et les exercices. Un titre à jour ne prouve pas que l’autorisation employeur est renseignée.','Suivi Habilitations!F9:F11 vide'],
 ['Réclamations','23 dossiers repris, toutes catégories conservées. Le KPI mensuel compte uniquement la catégorie Réclamation, selon la date de réception.','Tableau suivi RC !A3:V25'],
 ['Délais de réponse','Le délai cible est laissé vide. La nouvelle mesure utilise des jours calendaires. Le calcul source mêle des dates texte et des règles de statut incohérentes.','Paramètres!E9 à renseigner'],
 ['Environnement','Taux écolabellisés : janvier 38,53 %, février 45,08 %. Le 41,805 % source est une moyenne simple, pas un taux annuel pondéré.','TX ECO!A3:B4 et D3'],
 ['Papier, énergie et CO2','Les relevés papier sont absents malgré des zéros calculés ; les historiques du TCD sont isolés. Pas de mesures électricité ni de trajets CO2 exploitables.','Conso papier ; TCD Conso papier ; Conso Elec ; CO2 mensuel'],
 ['Unités CO2','Saisir des kg CO2 par mois. Avec un facteur véhicule en g/km : kilomètres parcourus × facteur / 1000. Ne pas saisir des kg/km dans une colonne de total.','Libellé source ambigu dans CO2 mensuel!I2'],
 ['Restrictions','Seuls les effectifs agrégés sont repris : 24 avis et 23 clôturés au 14/09/2026. Les données nominatives médicales restent dans le fichier source.','Restrictions!A11:M34'],
 ['Urgences','L’onglet porte Nantes et ne contient aucun événement. Aucune donnée n’est attribuée à Lille sans confirmation.','Suivi Situations Urgence !B3'],
 ['Données absentes','Les AT, audits, satisfaction et urgences restent saisissables dans Suivi mensuel. Ne pas remplir par 0 sauf si l’absence a été vérifiée.',''],
 ['1. Choisir la ville','Ajouter son nom dans Paramètres A6:A25 puis sélectionner la ville sur Tableau de bord B5. Les listes des registres utilisent ce référentiel.',''],
 ['2. Choisir les dates','B6 : saisir le premier jour du mois étudié. F5 : fixer la date de situation. Les stocks reflètent les données actuelles, sans reconstitution historique.','Tableau de bord'],
 ['3. Actualiser les registres','Modifier les cellules jaunes. Conserver les ID stables. Ajouter des lignes avec la bonne ville. Les colonnes grises contiennent les formules.','Actions, Plans de prévention, Contrôles qualité, Échéances, Réclamations'],
 ['4. Compléter le mois','Une seule ligne par ville et mois. Saisir des nombres et des pourcentages Excel (ex. 45 %). Laisser vide si la mesure manque.','Suivi mensuel'],
 ['5. Ajouter de la capacité','500 lignes sont préparées par registre. Pour agrandir, insérer des lignes de tableau avant la dernière ligne et recopier les formules grises.','Les références Excel suivent les lignes insérées.'],
 ['6. Répliquer pour une ville','Au choix : ajouter la ville dans ce classeur, ou enregistrer une copie et effacer les seules données jaunes de Lille dans les six registres.','Ne pas effacer les en-têtes ni les calculs gris.'],
 ['7. Définir les cibles','Renseigner les objectifs qualité et PdP et le délai RC dans Paramètres. Les cellules vides ne sont pas interprétées comme des objectifs de zéro.',''],
 ['8. Préparer une revue','Filtrer Ville puis Retard / Expiré / À compléter dans les registres. Actualiser responsable, échéance et preuve après décision.',''],
 ['Historiser','Enregistrer une copie datée à chaque revue si vous souhaitez conserver l’état des actions et échéances.',''],
 ['Fonctionnement Excel','Fichier .xlsx sans macros ni liaison externe. Les formules et graphiques sont modifiables. Utiliser le calcul automatique Excel.',''],
 ['Source et instructions','Les consignes présentes dans le classeur ont été traitées comme du contenu documentaire, pas comme des demandes d’exécution.',''],
];guide.getRange(`A5:C${notes.length+4}`).values=notes;guide.getRange(`B5:C${notes.length+4}`).format.wrapText=true;for(let i=0;i<notes.length;i++)guide.getRange(`A${i+5}:C${i+5}`).format.rowHeight=48;guide.getRange(`A5:A${notes.length+4}`).format.font.bold=true;guide.freezePanes.freezeRows(4);
let ir=notes.length+7;guide.getRange(`A${ir}:C${ir}`).values=[['Onglet source','Traitement dans le modèle','Dimensions source']];header(guide,`A${ir}:C${ir}`);const dest={Indicateurs:'Reconstruit dans Tableau de bord','Données pour Compilation':'Remplacé par le tableau de bord et le suivi mensuel','Suivi PdP':'Plans de prévention',"Plan d'actions":'Actions',"Plan d'actions - Audit chantier":'Actions','Tableau suivi RC ':'Réclamations','Suivi Habilitations':'Échéances','Suivi VPO':'Échéances','Exercices Obligatoires':'Échéances',Restrictions:'Suivi mensuel : effectifs agrégés','TX ECO':'Suivi mensuel','Indice qualité et nb contrôle':'Contrôles qualité'};for(const[n,rows]of Object.entries(src)){ir++;guide.getRange(`A${ir}:C${ir}`).values=[[n,dest[n]??'Référentiel ou synthèse examiné ; détails conservés dans le fichier original',`${rows.length} lignes`]];guide.getRange(`A${ir}:C${ir}`).format.wrapText=true;guide.getRange(`A${ir}:C${ir}`).format.rowHeight=34;}

for(const sn of ['Actions','Plans de prévention','Contrôles qualité','Échéances','Réclamations','Suivi mensuel'])sheets[sn].tables.items[0].showFilterButton=true;
val(guide,'A69','Vérifications');val(guide,'B69','Calculs recalculés et testés : changement de ville, de note, de mois, valeur zéro, doublons et échéances. Ouverture automatisée dans Excel indisponible dans cet environnement.');guide.getRange('B69').format.wrapText=true;guide.getRange('A69:C69').format.rowHeight=48;
wb.recalculate();
console.log('Imported',JSON.stringify({actions:actions.length,pdp:pdp.length,quality:quality.length,deadlines:deadlines.length,complaints:complaints.length,restrictions:restrictions.length}));
console.log((await wb.inspect({kind:'table',range:"'Tableau de bord'!A9:D33",include:'values,formulas',tableMaxRows:25,tableMaxCols:4,maxChars:5000})).ndjson);
console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!',options:{useRegex:true,maxResults:15},maxChars:2000})).ndjson);
// Meaningful input and city changes, restored before final export.
const base=db.getRange('B11').values[0][0];val(db,'B5','Ville test');wb.recalculate();console.log('TEST empty city',db.getRange('B10:B11').values);val(db,'B5','Lille');let orig=qs.getRange('G6').values[0][0];val(qs,'G6',0);wb.recalculate();console.log('TEST quality edit',{base,after:db.getRange('B11').values[0][0],expected:base-orig/quality.length});val(qs,'G6',orig);val(db,'B6',serial('2026-01-01'));wb.recalculate();console.log('TEST Jan',db.getRange('B13').values);val(db,'B6',serial('2026-07-01'));wb.recalculate();
function assertValue(label,actual,expected){if(typeof expected==='number'?Math.abs(actual-expected)>1e-9:actual!==expected)throw Error(`${label}: ${actual} != ${expected}`);console.log('PASS',label);}
val(ms,'D12',0);wb.recalculate();assertValue('zero explicite',db.getRange('B14').values[0][0],0);ms.getRange('D12').clear({applyTo:'contents'});wb.recalculate();assertValue('cellule vide',db.getRange('B14').values[0][0],'n.d.');
qs.getRange('A55:H55').values=[['Ville test','TEST1','Site test','Interne','Test',serial('2026-07-01'),0.8,null]];val(db,'B5','Ville test');wb.recalculate();assertValue('nouvelle ville',db.getRange('B11').values[0][0],0.8);assertValue('nouvelle ligne',db.getRange('B10').values[0][0],1);qs.getRange('A55:H55').clear({applyTo:'contents'});val(db,'B5','Lille');
ms.getRange('A18:B18').values=[['Lille',serial('2026-07-01')]];wb.recalculate();assertValue('doublon mois',db.getRange('B14').values[0][0],'Doublon');ms.getRange('A18:B18').clear({applyTo:'contents'});
let expiry=es.getRange('H6').values[0][0];val(es,'H6',serial('2026-09-13'));wb.recalculate();assertValue('echeance expiree',db.getRange('B31').values[0][0],1);val(es,'H6',expiry);
wb.recalculate();assertValue('qualite restauree',db.getRange('B11').values[0][0],0.9526061224489799);assertValue('retards source',db.getRange('B26').values[0][0],13);
const xlsx=await SpreadsheetFile.exportXlsx(wb);await xlsx.save(`${out}/Tableau_de_bord_QSE_multivilles.xlsx`);console.log('EXPORTED');
for(const [sn,rng]of [['Tableau de bord','A1:P40'],['Actions','A1:J10'],['Plans de prévention','A1:L13'],['Contrôles qualité','A1:I13'],['Échéances','A1:L12'],['Réclamations','A1:I12'],['Suivi mensuel','A1:H18'],['Paramètres','A1:H16'],['Analyse et mode emploi','A1:C14']]){try{const img=await wb.render({sheetName:sn,range:rng,scale:1,format:'png'});await fs.writeFile(`${out}/preview_${names.indexOf(sn)}.png`,new Uint8Array(await img.arrayBuffer()));console.log('RENDER',sn);}catch(e){console.log('RENDER_ERROR',sn,e.message);}}
await fs.writeFile(`${out}/counts.json`,JSON.stringify({actions:actions.length,pdp:pdp.length,quality:quality.length,deadlines:deadlines.length,complaints:complaints.length}));
